// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var $container;
    $container = $(".container");
    console.log($container);
    Path.map("#/A").to(function() {
      $("a:first").css("background", "red");
      return $(".container").load("pageA.html");
    });
    Path.map("#/B").to(function() {
      $("a:eq(2)").css("background", "red");
      return $(".container").load("pageB.html");
    });
    return Path.listen();
  });

}).call(this);

//# sourceMappingURL=script.map
