// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var $content;
    $content = $('#content');
    Path.map("#/linkA").to(function() {
      return $content.load("pageA.html");
    });
    Path.map("#/linkB").to(function() {
      return $content.load("pageB.html");
    });
    Path.map("#/linkC").to(function() {
      return $content.load("pageC.html");
    });
    return Path.listen();
  });

}).call(this);

//# sourceMappingURL=path.map
