// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var $content, addActiveLinkColor, removeActiveLinkColor;
    removeActiveLinkColor = function() {
      return $(".active").removeClass("active");
    };
    addActiveLinkColor = function() {};
    $content = $('#content');
    Path.map("#/linkA").to(function() {
      $content.load("pageA.html");
      removeActiveLinkColor();
      return $("a[href='#/linkA']").addClass("active");
    });
    Path.map("#/linkB").to(function() {
      $content.load("pageB.html");
      removeActiveLinkColor();
      return $("a[href='#/linkB']").addClass("active");
    });
    Path.map("#/linkC").to(function() {
      $content.load("pageC.html");
      removeActiveLinkColor();
      return $("a[href='#/linkC']").addClass("active");
    });
    return Path.listen();
  });

}).call(this);

//# sourceMappingURL=path.map
